###################################################################

# Created by write_sdc on Fri Sep 27 17:49:52 2024

###################################################################
set sdc_version 2.1

set_units -time ns -resistance kOhm -capacitance pF -voltage V -current mA
set_operating_conditions -max ss0p72vm40c -max_library                         \
N16ADFP_StdCellss0p72vm40c_ccs\
                         -min ff0p88v125c -min_library                         \
N16ADFP_StdCellff0p88v125c_ccs
set_wire_load_mode top
set_wire_load_model -name ZeroWireload -library N16ADFP_StdCellss0p72vm40c_ccs
set_max_area 0
set_ideal_network [get_ports clk]
create_clock [get_ports clk]  -period 0.626365  -waveform {0 0.313183}
set_input_delay -clock clk  0  [get_ports {a[31]}]
set_input_delay -clock clk  0  [get_ports {a[30]}]
set_input_delay -clock clk  0  [get_ports {a[29]}]
set_input_delay -clock clk  0  [get_ports {a[28]}]
set_input_delay -clock clk  0  [get_ports {a[27]}]
set_input_delay -clock clk  0  [get_ports {a[26]}]
set_input_delay -clock clk  0  [get_ports {a[25]}]
set_input_delay -clock clk  0  [get_ports {a[24]}]
set_input_delay -clock clk  0  [get_ports {a[23]}]
set_input_delay -clock clk  0  [get_ports {a[22]}]
set_input_delay -clock clk  0  [get_ports {a[21]}]
set_input_delay -clock clk  0  [get_ports {a[20]}]
set_input_delay -clock clk  0  [get_ports {a[19]}]
set_input_delay -clock clk  0  [get_ports {a[18]}]
set_input_delay -clock clk  0  [get_ports {a[17]}]
set_input_delay -clock clk  0  [get_ports {a[16]}]
set_input_delay -clock clk  0  [get_ports {a[15]}]
set_input_delay -clock clk  0  [get_ports {a[14]}]
set_input_delay -clock clk  0  [get_ports {a[13]}]
set_input_delay -clock clk  0  [get_ports {a[12]}]
set_input_delay -clock clk  0  [get_ports {a[11]}]
set_input_delay -clock clk  0  [get_ports {a[10]}]
set_input_delay -clock clk  0  [get_ports {a[9]}]
set_input_delay -clock clk  0  [get_ports {a[8]}]
set_input_delay -clock clk  0  [get_ports {a[7]}]
set_input_delay -clock clk  0  [get_ports {a[6]}]
set_input_delay -clock clk  0  [get_ports {a[5]}]
set_input_delay -clock clk  0  [get_ports {a[4]}]
set_input_delay -clock clk  0  [get_ports {a[3]}]
set_input_delay -clock clk  0  [get_ports {a[2]}]
set_input_delay -clock clk  0  [get_ports {a[1]}]
set_input_delay -clock clk  0  [get_ports {a[0]}]
set_input_delay -clock clk  0  [get_ports {b[31]}]
set_input_delay -clock clk  0  [get_ports {b[30]}]
set_input_delay -clock clk  0  [get_ports {b[29]}]
set_input_delay -clock clk  0  [get_ports {b[28]}]
set_input_delay -clock clk  0  [get_ports {b[27]}]
set_input_delay -clock clk  0  [get_ports {b[26]}]
set_input_delay -clock clk  0  [get_ports {b[25]}]
set_input_delay -clock clk  0  [get_ports {b[24]}]
set_input_delay -clock clk  0  [get_ports {b[23]}]
set_input_delay -clock clk  0  [get_ports {b[22]}]
set_input_delay -clock clk  0  [get_ports {b[21]}]
set_input_delay -clock clk  0  [get_ports {b[20]}]
set_input_delay -clock clk  0  [get_ports {b[19]}]
set_input_delay -clock clk  0  [get_ports {b[18]}]
set_input_delay -clock clk  0  [get_ports {b[17]}]
set_input_delay -clock clk  0  [get_ports {b[16]}]
set_input_delay -clock clk  0  [get_ports {b[15]}]
set_input_delay -clock clk  0  [get_ports {b[14]}]
set_input_delay -clock clk  0  [get_ports {b[13]}]
set_input_delay -clock clk  0  [get_ports {b[12]}]
set_input_delay -clock clk  0  [get_ports {b[11]}]
set_input_delay -clock clk  0  [get_ports {b[10]}]
set_input_delay -clock clk  0  [get_ports {b[9]}]
set_input_delay -clock clk  0  [get_ports {b[8]}]
set_input_delay -clock clk  0  [get_ports {b[7]}]
set_input_delay -clock clk  0  [get_ports {b[6]}]
set_input_delay -clock clk  0  [get_ports {b[5]}]
set_input_delay -clock clk  0  [get_ports {b[4]}]
set_input_delay -clock clk  0  [get_ports {b[3]}]
set_input_delay -clock clk  0  [get_ports {b[2]}]
set_input_delay -clock clk  0  [get_ports {b[1]}]
set_input_delay -clock clk  0  [get_ports {b[0]}]
set_input_delay -clock clk  0  [get_ports c_in]
set_output_delay -clock clk  0  [get_ports {q[32]}]
set_output_delay -clock clk  0  [get_ports {q[31]}]
set_output_delay -clock clk  0  [get_ports {q[30]}]
set_output_delay -clock clk  0  [get_ports {q[29]}]
set_output_delay -clock clk  0  [get_ports {q[28]}]
set_output_delay -clock clk  0  [get_ports {q[27]}]
set_output_delay -clock clk  0  [get_ports {q[26]}]
set_output_delay -clock clk  0  [get_ports {q[25]}]
set_output_delay -clock clk  0  [get_ports {q[24]}]
set_output_delay -clock clk  0  [get_ports {q[23]}]
set_output_delay -clock clk  0  [get_ports {q[22]}]
set_output_delay -clock clk  0  [get_ports {q[21]}]
set_output_delay -clock clk  0  [get_ports {q[20]}]
set_output_delay -clock clk  0  [get_ports {q[19]}]
set_output_delay -clock clk  0  [get_ports {q[18]}]
set_output_delay -clock clk  0  [get_ports {q[17]}]
set_output_delay -clock clk  0  [get_ports {q[16]}]
set_output_delay -clock clk  0  [get_ports {q[15]}]
set_output_delay -clock clk  0  [get_ports {q[14]}]
set_output_delay -clock clk  0  [get_ports {q[13]}]
set_output_delay -clock clk  0  [get_ports {q[12]}]
set_output_delay -clock clk  0  [get_ports {q[11]}]
set_output_delay -clock clk  0  [get_ports {q[10]}]
set_output_delay -clock clk  0  [get_ports {q[9]}]
set_output_delay -clock clk  0  [get_ports {q[8]}]
set_output_delay -clock clk  0  [get_ports {q[7]}]
set_output_delay -clock clk  0  [get_ports {q[6]}]
set_output_delay -clock clk  0  [get_ports {q[5]}]
set_output_delay -clock clk  0  [get_ports {q[4]}]
set_output_delay -clock clk  0  [get_ports {q[3]}]
set_output_delay -clock clk  0  [get_ports {q[2]}]
set_output_delay -clock clk  0  [get_ports {q[1]}]
set_output_delay -clock clk  0  [get_ports {q[0]}]
